from typing import List, Dict, Any

class LispGenerator:
    """Generates formatted LISP code from parsed blocks and instructions."""
    
    def __init__(self):
        self.indent_level = 0

    def generate(self, func_name: str, args: List[str], blocks: List[Dict[str, Any]], strings: List[Dict[str, Any]]) -> str:
        """Generate full LISP function source."""
        lines = []
        lines.append(';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;')
        lines.append(';; Generated by Unified FAS2LSP Decompiler')
        lines.append(';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;')
        lines.append('')
        
        args_str = " ".join(f"/{a}" for a in args) if args else ""
        lines.append(f"(defun {func_name} ({args_str})")
        
        self.indent_level = 1
        for block in blocks:
            if block['type'] == 'call':
                inst = block['content'][0]
                func_call = inst.get('string_ref', 'UNKNOWN_FUNC')
                lines.append(self._indent(f"({func_call} ...)"))
            elif block['type'] == 'expr':
                # Reconstruct expressions from instructions
                expr_str = self._reconstruct_expression(block['content'])
                if expr_str:
                    lines.append(self._indent(expr_str))
                    
        lines.append(")")
        lines.append("")
        lines.append(";; End of file")
        
        return "\n".join(lines)

    def _indent(self, text: str) -> str:
        return "  " * self.indent_level + text

    def _reconstruct_expression(self, instructions: List[Dict[str, Any]]) -> str:
        """Heuristically reconstruct LISP expressions."""
        # Find all strings referenced in this block
        refs = [inst['string_ref'] for inst in instructions if 'string_ref' in inst]
        if not refs:
            return ";; [Code segment with no string references]"
            
        # If we see a keyword, try to form an expression around it
        keywords = ['princ', 'setq', 'getstring', 'namedobjdict', 'if', 'progn']
        
        main_kw = None
        for r in refs:
            if r.lower() in keywords:
                main_kw = r
                break
        
        if main_kw:
            others = [r for r in refs if r != main_kw]
            return f"({main_kw} {' '.join(others[:2])})"
        
        return f";; Extracted tokens: {' '.join(refs[:5])}"
