;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Decompiled from: PDI.fas
;; Generated by FAS4 Decompiler (resource-aware reconstruction)
;; Names are recovered from decrypted FAS4 metadata where possible.
;; Control flow reconstruction is still partial for complex branch patterns.
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; Recovered strings (first 12):
;;   \nNo dictionary item(s) matched pattern. 
;;    dictionary item(s) purged. 
;;   \n
;;   ".
;;   \n Purging dictionary "
;;   \n Purge Dictionary Items <Enter case sensitive pattern>: 
;;   \n NOTE: Purging "ACAD_*" may corrupt the drawing file. 
;;   \n ======================================================
;;   \n     
;;   \n ------------------------------------------------------
;;   \n Current Dictionary List: 

;; Referenced symbols: MSG, A
(defun msg ()
  (a 'msg)
  ;; jump +39
)

;; Original arg hints: B
;; Referenced symbols: NAMEDOBJDICT, _al-bind-alist, CDR, CAR, =, C, CONS, N, ACAD_STRLSORT, STRCAT
;; Referenced strings: \n     , \n ======================================================, \n Purge Dictionary Items <Enter case sensitive pattern>: 
(defun c:pdi (b)
  (setq c nil)
  (setq n nil)
  (setq gvar_31_princ nil)
  (setq *error* nil)
  (namedobjdict)
  (setq gvar_28_entget '_al-bind-alist)
  (setq c (car (car (_al-bind-alist))))
  (while c
    (if (cons (car (car c)) 3)
      (progn
        (setq n (cons (car (car c)) n))
      )
      (progn
      )
    )
    (if (car c)
      (progn
        (setq c (car c))
      )
      (progn
        (setq c nil)
      )
    )
  )
  (_al-bind-alist 'acad_strlsort)
  (princ "\n     ")
  (setq b (strcat n))
  ;; init-args 3: 'c, nil
  (foreach c b
    (_al-bind-alist (getstring "\n ======================================================" c))
  )
  (_al-bind-alist 'textscr)
  (princ "\n Purge Dictionary Items <Enter case sensitive pattern>: ")
  (textscr)
  (strlen 'strlen)
  ;; if (dictremove (vl-acad-defun (setq gvar_31_princ (strlen 'strlen))) 0) then jump +173
  (setq *error* 0)
  (setq b n)
  ;; init-args 3: 'c, nil
  (foreach c b
    (if (vl-acad-defun c gvar_31_princ)
      (progn
        (vl-acad-defun (_al-bind-alist) c)
        (_al-bind-alist (wcmatch '1+ c "\n"))
        (setq *error* (itoa *error*))
      )
      (progn
      )
    )
  )
)

;; Referenced symbols: *ERROR*, DICTREMOVE, NAMEDOBJDICT, vl-ACAD-defun
;; Referenced strings:  dictionary item(s) purged. 
(defun fas_init_2 ()
  (if (dictremove *error* 0)
    (progn
      (_al-bind-alist (wcmatch " dictionary item(s) purged. " (vl-acad-defun *error*) '((cons 20 59) (cons 0 517))))
    )
    (progn
      (_al-bind-alist 'vl-acad-defun)
    )
  )
  ;; jump +0
  (setq c nil)
  (setq n nil)
  (setq gvar_31_princ nil)
  (setq *error* nil)
  (namedobjdict)
)

(princ) ;; Silent load